import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.locator('body').click();
    await page.goto('http://localhost:4200/');
    await page.locator('div').filter({ hasText: /^play_arrow PLAY NOWBlue Beetlestar7\.2 \/102023$/ }).locator('div').first().click();
    await page.locator('div').filter({ hasText: /^play_arrow PLAY NOWBlue Beetlestar7\.2 \/102023$/ }).locator('div').nth(1).click();
    await page.locator('div').filter({ hasText: /^play_arrow PLAY NOWBlue Beetlestar7\.2 \/102023$/ }).locator('div').nth(1).click();
    await page.getByRole('navigation').getByRole('link', { name: 'Home (current)' }).click();
    await page.locator('.btn').first().click();
    await page.getByRole('button', { name: 'star_border Remove Favorite' }).click();
    await page.locator('div:nth-child(2) > .btn').first().click();
    await page.getByRole('link', { name: 'My Favorites' }).click();
    await page.getByText('English').click();
    await page.getByRole('navigation').getByRole('link', { name: 'Home (current)' }).click();
    await page.getByText('English').click();
    await page.getByText('Indonesian').click();
    await page.getByRole('navigation').getByRole('link', { name: 'Movies' }).click();
    await page.getByPlaceholder('Search for movies...').click();
    await page.getByPlaceholder('Search for movies...').fill('meg');
    await page.getByPlaceholder('Search for movies...').press('Enter');
    await page.getByPlaceholder('Search for movies...').press('Control+a');
    await page.getByPlaceholder('Search for movies...').fill('');
    await page.getByPlaceholder('Search for movies...').press('Enter');
    await page.getByRole('navigation').getByRole('link', { name: 'Genres' }).click();
    await page.getByRole('navigation').getByRole('link', { name: 'Genres' }).click();
    await page.getByRole('navigation').getByRole('link', { name: 'TV Shows' }).click();
    await page.getByRole('navigation').getByRole('link', { name: 'Genres' }).click();
    await page.getByRole('navigation').getByRole('link', { name: 'Genres' }).click();
    await page.locator('button').filter({ hasText: 'Animasi' }).first().click();
    await page.getByRole('navigation').getByRole('link', { name: 'TV Shows' }).click();
    await page.getByRole('link', { name: 'My Favorites' }).click();
    await page.goto('http://localhost:4200/favorites');
    await page.getByRole('button', { name: 'star_border Remove Favorite' }).click();
    await page.getByRole('navigation').getByRole('link', { name: 'Home (current)' }).click();
});